### PR TITLE
epochal discrete CTMC model bug fixes

### PR DESCRIPTION
**Pull request by jsigao**
This pull request contains a few bug-fix commits related to the epochal branch model. The second and third commits (`f635eb0` and `9f7df12`) are quite minor (both in terms of the consequences and the changes made) and hopefully can be self-explanatory, so I'll focus on the first commit (while the fourth commit simply involves some comment edits that I forgot to make in the first commit) here.

The first commit (`59fc185`) attempts to fix an issue with the order of matrices fetched by the getBranchModelMapping function. This function is a member of the `EpochalBranchModel` class, which implements a model where the a discrete CTMC (substitution or dispersal) model can vary over time epochs. When a branch overlaps with multiple time epochs, the transition-probability (P) matrix of this branch is computed as the product (i.e., convolution) of epochal P matrices along the branch ([Eg. 7 of Bielejec et al., 2014](https://academic.oup.com/sysbio/article/63/4/493/2848077#M7)). In the convolution, these P matrices should be ordered from the parent node to the child node.

It seems that the current implementation instead ordered the matrices from child to parent in the `getBranchModelMapping` function, and there doesn't seem to involve any reversal of the order after invoking the function (judging from the `updateTransitionMatrices` and `convolveMatrices` functions of the `SubstitutionModelDelegate` class). Accordingly, I edited the `getBranchModelMapping` function so that it returns an epochal-model mapping ordered from parent to child along a branch.

This is my first time submitting a pull request to BEAST; please let me know if I misinterpreted anything or failed to follow the preferred coding style in my edits. Thank you in advance for reviewing this PR.

### CODE REVIEW

**Review by msuchard — CHANGES_REQUESTED** [review]
@jsigao :

1.  please provide a `ci/TestXML/*.xml` that demonstrates that there really is a bug in the convolution order ... or email me an example.
2.  please also target `hmc-clock` since this is _breaking_ behavior.

**Comment by jsigao** [comment]
Dear @msuchard -- thanks very much for your review! I'll make the requested changes to this PR and get back to you as soon as I can.

**Comment by jsigao** [comment]
Dear @msuchard -- sorry for the delay in making the requested changes to this pull request. Please see this [synopsis.pdf](https://github.com/beast-dev/beast-mcmc/files/9050710/synopsis.pdf) document for a brief summary of an experiment I did attempting to demonstrate the issue with the order of P matrices in the convolution. (The supplementary files that I used to perform the experiment is available in this [Porder_test.zip](https://github.com/beast-dev/beast-mcmc/files/9050721/Porder_test.zip) folder).

Please let me know if there is anything unclear or missing in the experiment. I have also changed the target branch of this pull request to `hmc-clock`.

**Comment by msuchard** [comment]
hi @jsigao -- thanks for the great work here!   instead of a `merge pull request` here, I did a manual edit (in commits 667b74c77dec8a6c10c972c7c9ca39079ceb67ef and 7913ef9597ad702f3b818d33ea1ca61d783e938b) just because i was not too happy with the `ArrayList.add(0, )` reordering.

**Comment by jsigao** [comment]
Dear @msuchard -- that sounds great. Thanks very much for reviewing and approving the pull request (and adding the unit-test file)!

**Pull request closed without merging**
